server:
  port: 8083
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name:
      cluster-nodes: 192.168.42.134:9300
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 127.0.0.1
    virtual-host: /leyou
    username: leyou
    password: leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
ribbon:
  eureka:
    enabled: true