server:
  port: 10086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    register-with-eureka: false
    fetch-registry: false
spring:
  application:
    name: leyou-registry
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000
ribbon:
  eureka:
    enabled: true